trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core sdk"
    inputs:
      packageType: "sdk"
      version: "6.0.x"
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      testRunTitle: "xUNit Test Run"

  - task: DotNetCoreCLI@2
    displayName: "dotnet publish"
    inputs:
      command: publish
      publishWebProjects: false
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
  - task: PublishBuildArtifacts@1
    displayName: "publish artifacts"
